[tools]
"github:BurntSushi/ripgrep" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"
"github:LuaLS/lua-language-server" = "latest"
"github:axllent/mailpit" = "latest"
"github:cli/cli" = "latest"
"github:composer/composer" = { version = "latest", bin = "composer" }
"github:jqlang/jq" = "latest"
"github:laravel/lsp" = { version = "latest", bin = "laravel-lsp" }
"github:junegunn/fzf" = "latest"
"github:neovim/neovim" = "latest"
"github:sharkdp/fd" = "latest"
"github:starship/starship" = "latest"
"github:tree-sitter/tree-sitter" = "latest"
"github:yt-dlp/yt-dlp" = "latest"
"gitlab:gitlab-org/cli" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:intelephense" = "latest"
"npm:typescript" = "latest"
"core:go" = "latest"
"core:node" = "lts"
"github:anomalyco/opencode" = "latest"
